- name: variables
  hosts: localhost
  vars: # variable declaration
    Course: "Terraform"
    Trainer: "SK"
    Duration: "120 hours"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}}"
